name: Kyobo → Notion (auto fill)

on:
  schedule:
    - cron: "*/5 * * * *"  # GitHub Actions' practical minimum interval
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: kyobo-notion
  cancel-in-progress: true

jobs:
  run:
    # Uncomment and set your username to ensure the workflow only runs on your repo (helps if the repo gets forked)
    # if: github.repository_owner == 'YOUR_GH_USERNAME'
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.BOOKS_DB_ID }}
      # Optional property names (match your Notion DB)
      TITLE_PROP: "책 제목"
      AUTHOR_PROP: "저자"
      PUBLISHER_PROP: "출판사"
      PAGES_PROP: "페이지"
      GENRE_PROP: "장르"
      STATUS_PROP: "상태"
      KY_URL_PROP: "교보 URL"
      REQUEST_PROP: "수집요청"
      READ_PAGES_PROP: "읽은 페이지"
      # GENRE_MAP_JSON: '{"소설":"문학","과학":"자연/과학"}'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

   - name: Install dependencies
  shell: bash
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m playwright install --with-deps chromium


      - name: Install Playwright (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper → Notion updater
        run: |
          # Adjust the entry point if your script has a different filename/path
          if [ -f kyobo_to_notion.py ]; then
            python kyobo_to_notion.py
          elif [ -f scripts/kyobo_to_notion.py ]; then
            python scripts/kyobo_to_notion.py
          else
            echo "::error::Cannot find kyobo_to_notion.py at repo root or scripts/"
            exit 1
          fi
