name: Kyobo → Notion (auto fill)

on:
  schedule:
    - cron: "*/1 * * * *"   # 1분마다 (UTC 기준)
  workflow_dispatch: {}      # 수동 실행 버튼

concurrency:
  group: kyobo-notion
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID:  ${{ secrets.DATABASE_ID }}

      # ── 노션 속성명 (네 DB와 다르면 수정) ──
      TITLE_PROP:       책 제목
      AUTHOR_PROP:      저자
      PUBLISHER_PROP:   출판사
      PAGES_PROP:       페이지
      GENRE_PROP:       장르
      STATUS_PROP:      상태
      KY_URL_PROP:      교보 URL
      REQUEST_PROP:     수집요청
      READ_PAGES_PROP:  읽은 페이지

      # ── 장르 매핑 테이블 ──
      GENRE_MAP_JSON: >
        {
          "과학,자연,물리,화학,생물,천문": "과학",
          "수학,미적분,통계": "수학",
          "컴퓨터,IT,프로그래밍,코딩,인공지능,데이터": "IT",
          "소설,장편,단편,문학": "소설",
          "에세이,수필": "에세이",
          "인문,철학,심리": "인문",
          "역사,세계사,한국사": "역사",
          "경제,경영,마케팅,회계,재테크": "경영/경제",
          "자기계발,자기개발,동기": "자기계발"
        }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper → Notion updater
        run: |
          python kyobo_to_notion.py
