# .github/workflows/kyobo.yml
name: Kyobo → Notion (every 5 min)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: kyobo-notion
  cancel-in-progress: true

jobs:
  run:
    environment: production           # 너가 만든 Environment 이름으로 수정해도 됨
    runs-on: ubuntu-latest
    timeout-minutes: 12

    env:
      # --- REQUIRED (레포/환경 시크릿 중 아무데나 있어도 됨) ---
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID:  ${{ secrets.DATABASE_ID }}

      # --- OPTIONAL: Notion property names ---
      TITLE_PROP: "책 제목"
      AUTHOR_PROP: "저자"
      PUBLISHER_PROP: "출판사"
      PAGES_PROP: "페이지"
      GENRE_PROP: "장르"
      STATUS_PROP: "상태"
      KY_URL_PROP: "교보 URL"
      REQUEST_PROP: "수집요청"
      READ_PAGES_PROP: "읽은 페이지"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Install Playwright browser if used
        run: |
          if python -c "import importlib.util,sys; sys.exit(0 if importlib.util.find_spec('playwright') else 1)"; then
            python -m playwright install --with-deps chromium
          else
            echo "playwright not detected; skipping browser install"
          fi

      - name: Debug env (quick check)
        run: |
          [ -n "$NOTION_TOKEN" ] || { echo "NOTION_TOKEN is empty"; exit 1; }
          [ -n "$DATABASE_ID"  ] || { echo "DATABASE_ID is empty";  exit 1; }

      - name: Run scraper → Notion updater
        run: |
          if [ -f kyobo_to_notion.py ]; then
            python kyobo_to_notion.py
          elif [ -f scripts/kyobo_to_notion.py ]; then
            python scripts/kyobo_to_notion.py
          else
            echo "::error::Cannot find kyobo_to_notion.py at repo root or scripts/"
            exit 1
          fi
