name: Kyobo → Notion (every 5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # GitHub Actions practical minimum interval
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: kyobo-notion
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run:
    # 필요하면 포크 방지용으로 Owner 체크 추가:
    # if: github.repository_owner == 'YOUR_GH_USERNAME'
    runs-on: ubuntu-latest
    timeout-minutes: 12
    env:
      # --- REQUIRED SECRETS ---
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.BOOKS_DB_ID }}  # <- 너의 DB ID 시크릿 이름이 다르면 여기만 수정

      # --- OPTIONAL: Notion property names (네 DB에 맞게 수정 가능) ---
      TITLE_PROP: "책 제목"
      AUTHOR_PROP: "저자"
      PUBLISHER_PROP: "출판사"
      PAGES_PROP: "페이지"
      GENRE_PROP: "장르"
      STATUS_PROP: "상태"
      KY_URL_PROP: "교보 URL"
      REQUEST_PROP: "수집요청"
      READ_PAGES_PROP: "읽은 페이지"
      # KY_URL_PROP_TYPE: "rich_text"  # 교보 URL이 리치텍스트일 때만 사용
      # PAGE_SIZE: "50"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: (Optional) Install Playwright browser if used
        run: |
          # playwright 패키지가 설치되어 있을 때만 브라우저 설치
          if python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('playwright') else 1)"; then
            python -m playwright install --with-deps chromium
          else
            echo "playwright not detected; skipping browser install"
          fi

      - name: Run scraper → Notion updater
        run: |
          # 엔트리포인트 경로에 맞게 자동 탐색
          if [ -f kyobo_to_notion.py ]; then
            python kyobo_to_notion.py
          elif [ -f scripts/kyobo_to_notion.py ]; then
            python scripts/kyobo_to_notion.py
          else
            echo "::error::Cannot find kyobo_to_notion.py at repo root or scripts/"
            exit 1
          fi
