name: Kyobo → Notion (auto fill)

on:
  schedule:
    - cron: "*/5 * * * *"   # GitHub 최소 간격: 5분
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: kyobo-notion
  cancel-in-progress: true

jobs:
  run:
    # 포크에서 돌지 않게(원 저장소만) 하고 싶다면 주석 해제
    # if: github.repository_owner == 'YOUR_GH_USERNAME'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.BOOKS_DB_ID }}
      TITLE_PROP: "책 제목"
      AUTHOR_PROP: "저자"
      PUBLISHER_PROP: "출판사"
      PAGES_PROP: "페이지"
      GENRE_PROP: "장르"
      STATUS_PROP: "상태"
      KY_URL_PROP: "교보 URL"
      REQUEST_PROP: "수집요청"
      READ_PAGES_PROP: "읽은 페이지"
      # 선택: 장르 매핑 쓰면 JSON으로
      # GENRE_MAP_JSON: '{"소설":"문학","과학":"자연/과학"}'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright (Chromium)
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper → Notion updater
        run: |
          python kyobo_to_notion.py
